### PR TITLE
Made a few changes

### PR DESCRIPTION
**Pull request by Feel65**
I did this all on mobile, I’ll look it over later

### CODE REVIEW

**Comment by KTibow** [comment]
minor issue: loudclient has been superseded by mart

**Comment by Feel65** [comment]
im gonna shit yourself so hard rn kti


WHY ISNT MART WHAT KM EDITING
WHY ISNT MART IN THE “OFFICIAL” SKYCLIENT REPO

RHDHWJEGKSHSGSKEFUSHSHSISGWIABBSHSJSUSHGSGSG FUDKGXOCGEOSBSJSJGSGS. I WILL DO IT AGAIN LATER JUST ASK ME WHEN. GAWD DAMN

**Comment by KTibow** [comment]
https://github.com/KTibow/Mart
image
also do you mean "i'm gonna shit myself" or "you're gonna shit yourself"

**Comment by Feel65** [comment]
I AM GOING TO SHIT YOURSELF

**Comment by Ascynx** [comment]
> I AM GOING TO SHIT YOURSELF
so true

**Pull request closed without merging**
