### PR TITLE
Funfacts.txt Added text

### PR DESCRIPTION
**Pull request by Nekron297**

### CODE REVIEW

**Comment by KTibow** [comment]
lmao

**Comment by nacrt** [comment]
who is merkoku

**Comment by Nekron297** [comment]
Merkoku is my friend Merlock. He is in VC with me, and mentioned adding it to the SkyClient loading screen. But he does not know how to navigate GitHub at all, so asked me if i could do it for him, lmao

**Comment by RayDeeUx** [comment]
NOPE NOPE NOPE NOPE NOPE.

last thing we need is 25k people misunderstanding that skyclient is partnering with content creators

@KTibow <@794377681331945524> close this ASAP.

**Comment by KTibow** [comment]
yeah i guess i won't merge this to prevent misunderstanding

**Comment by nacrt** [comment]
that's kind of a way too strong and over the top reaction from ray, as always

**Comment by nacrt** [comment]
@Nekron297 unfortunately we don't want to get involved too much with youtubers, although i'm sure he is a nice guy

**Comment by nacrt** [comment]
maybe we'll do something like that but for a long list of creators who we think are cool, instead of singling out individual creators

**Comment by Nekron297** [comment]
kinda cringe, but what ever

**Comment by RayDeeUx** [comment]
ah yes, it's cringe to not open the Pandora's box of "hey let me plug my social media into a mod pack 25k people use because haha funny"

**Comment by Mqisty** [comment]
why ery always act like every decision but his will end the world

**Comment by Ascynx** [comment]
> why ery always act like every decision but his will end the world

because it's true, duhh

**Comment by ShinyaHir** [comment]
> ah yes, it's cringe to not open the Pandora's box of "hey let me plug my social media into a mod pack 25k people use because haha funny"

ery its not that deep

**Comment by Nekron297** [comment]
I mean, whats the difference between advertising a twitch, as opposed to a sound cloud? Because there is a screen that tells you to check out someones music. Is it because its not a direct link? So if I did the same hex thing but didnt mention twitch and just put Merkoku what would the difference be

**Comment by UnderscoreRayless** [comment]
There would be no difference. We have no obligation to advertise some random person

**Comment by Nekron297** [comment]
Exactly. So then the one saying to look at some dudes music should either be removed, or mine should be allowed with different wording, not mentioning twitch in any way shape or form

**Comment by UnderscoreRayless** [comment]
where?? We don't advertise anyone's music

**Comment by KTibow** [comment]
zetvue put smth in referencing themself as part of one of their prs

**Comment by UnderscoreRayless** [comment]
> zetvue put smth in referencing themself as part of one of their prs

Oh the cipher, yeah but Zetvue's done a lot for skyclient, I don't really know who merkoku is and they seem to be some random person. This isn't the place to plug your social media

**Pull request closed without merging**
