### PR TITLE
Changed Maximusbar to Maya

### PR DESCRIPTION
**Pull request by Maximusbarcz**

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
man never realized how boring kt’s is just “skyclient dev” not even any damn capitals

**Comment by KTibow** [comment]
i like it that way, it represents what i do fine

**Comment by KTibow** [comment]
also @MicrocontrollersDev its colored and chroma if applicable so not the most boring thing

**Comment by MicrocontrollersDev** [comment]
kt moment 💀

**Pull request merged**
