### PR TITLE
theres gotta be a better way

### PR DESCRIPTION
**Pull request by Mqisty**
kti for the love of god how do i do this better i am going to kms theres gotta be a better way

### CODE REVIEW

**Comment by KTibow** [comment]
Use tailwind margin (`m-4` is 1rem) and apply it to the bottom element, not the body

**Comment by Mqisty** [comment]
~~(what bottom element)~~

**Comment by KTibow** [comment]
the credits list element

**Comment by KTibow** [comment]
closed in favor of #30

**Pull request closed without merging**
